version: '2'
services:
  captcha-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/captcha/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=captcha
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
